### ISSUE TITLE
RI artefact packages API classes shading the API jar contents 

### ISSUE THREAD

**Issue by dwhitla** [eclipse-ee4j/angus-mail#111]
Please stop shading API classes by packaging them in the RI jar. This is a terrible practice. Instead please include a compile time maven dependency on a specific version in your own POM.
 
Consumers of the API already have a (potentially transitive) dependency on the API jar and duplicating the API in your artefact causes two copies of each included class to be available at runtime. It is not guaranteed by platform runtimes which copy a class loader will load. This causes extremely hard to trace bugs if your shaded classes differ from the API classes.

**Comment by lukasj** [comment]
What exactly is blocking one to use the recommended set of dependencies which is to use API and arbitrary runtime? All possible configurations are listed at the website - https://eclipse-ee4j.github.io/angus-mail/#Download_Angus_Mail_Release

**Comment by dwhitla** [comment]
Because thats not how you are supposed to use Maven.

**Comment by lukasj** [comment]
I understand it may sound surprising but maven is not the one and only buildsystem available and certainly not the only one used by users of mail. There are cases where users find it more convenient to have just one jar and it may be their only dependency. If you don't like it, don't use it, it's not for you, and choose the set of dependencies which works the best for you

**Comment by dwhitla** [comment]
You can drop the arrogance. Obviously Maven (and Gradle) is not the only build system but if you are going to use it and support it you should make it actually work.
BTW Maven is more widely used than any other build or dependency management system in the Java ecosystem.

**Comment by lukasj** [comment]
> You can drop the arrogance. 

I always find it funny when those hitting the comment button too early claiming assumptions about "global knowledge" giving no definition of what that "global knowledge" is are editing their message once they got answer they apparently did not expect, so they can blame the author of the answer for anything.

But let's stop this. I assume we got lost in translation... and clearly the text does NOT cover emotions ;-)

> BTW Maven is more widely used than any other build or dependency management system in the Java ecosystem.
You are breaking the 99% case for 1% of users who can just have two jars and will not duplicate anything.

No, your understanding of the current state is wrong.
Up to EE9, there was no way to use standalone API with arbitrary arbitrary runtime and only the "bundle" existed
In EE 10 - the API got separated and from this release, one can use the right maven set of dependencies

The reality is that EE 10 version (API 2.1) actually _fixed_ things and is actually advertising the move towards this setup in the docs, while it also keeps the "old" bundle for those who for whatever reason don't want to or can't move towards standalone artifacts.

So the question is: What exactly is not possible to be done in a way you want it to be with what is currently in place?
* [Docs](https://eclipse-ee4j.github.io/angus-mail/#Download_Angus_Mail_Release) is primarily using API & runtime artifacts
* [EE API](https://github.com/jakartaee/jakartaee-api/blob/master/jakartaee-bom/pom.xml#L243) uses  just the API - exactly in a way you describe

What am I missing? Is it just the actual existence of the "bundle"? Then sorry, it is not going away for the time beeing

**Comment by pzygielo** [comment]
@dwhitla 
Would it work for you to switch/fix on your side from
```xml
    <dependency>
        <groupId>org.eclipse.angus</groupId>
        <artifactId>jakarta.mail</artifactId><!-- Note from the linked docs:
           Alternatively, jakarta.mail.jar, 
              which includes Jakarta Mail APIs with Angus Mail runtime
           as a default provider in one jar file, can be used,
           ie to limit the length of the classpath or number of dependencies -->
        <scope>runtime</scope>
    </dependency>
```
to
```xml
    <dependency>
        <groupId>org.eclipse.angus</groupId>
        <artifactId>angus-mail</artifactId>
        <scope>runtime</scope>
    </dependency>
```

**Comment by dwhitla** [comment]
Also breaks JPMS by duplicating the module name `jakarta.mail` and results in ServiceLoader failure in projects which include dependencies which `requires jakarta.mail` and ship a compile dependency on the API artefact.

**Comment by dwhitla** [comment]
> I always find it funny when those hitting the comment button too early claiming assumptions about "global knowledge" giving no definition of what that "global knowledge" is are editing their message once they got answer they apparently did not expect, so they can blame the author of the answer for anything.

There was no "claim of 'global knowledge'" and the  comment was edited BEFORE you replied to it as I realised the initial comment too terse to explain why shading dependencies in Maven is a problem and no-one had yet replied. The condescension embedded in "I understand it may sound surprising" was not constructive and just turns people off trying to provide feedback.
 
> No, your understanding of the current state is wrong. Up to EE9, there was no way to use standalone API with arbitrary arbitrary runtime and only the "bundle" existed In EE 10 - the API got separated and from this release, one can use the right maven set of dependencies

Yes - all the links I found to the RI for `jakarta-mail` pointed to the bundle instead of the standalone implementation. As this has been a long standing practice in the EE and Jakarta RI jars it gave the impression that the bundle WAS the RI. The naming didn't clarify this for me. In Maven the common idiom for "bundling" like this is a "bundle" POM that just declares dependencies on the artefacts being bundled.
Thank you @pzygielo for pointing this out.

> What am I missing? Is it just the actual existence of the "bundle"? Then sorry, it is not going away for the time beeing

No the existence of the bundle is not an issue. My last comment about JPMS and ServiceLoader is also based upon trying to use the bundle in an application where other dependencies already declare `requires` on the API module.

**Comment by dwhitla** [comment]
FWIW this was all caused by Spring Boot including `org.eclipse.angus:jakarta.mail` as a dependency instead of `org.eclipse.angus:angus-mail` while also depending upon `jakarta.mail:jakarta.mail-api`.

**Comment by lukasj** [comment]
> Please stop shading API classes by packaging them in the RI jar. This is a terrible practice. Instead please include a compile time maven dependency on a specific version in your own POM.

does not answer any question in the bug report template which apparently had to be ignored; pointer to the documentation which lists possible usage scenarios was given in the initial comment, given the response which followed - was likely ignored as well. The way the initial report was written demands someone to just do the work ignoring whatever options the project offers and more importantly documents, giving impression project maintainers are ..., nothing else.

> Yes - all the links I found to the RI for jakarta-mail pointed to the bundle instead of the standalone implementation. 

Jakarta has no idea what RI is. What does "all the links I found" mean? Which links are you referring to?

> Also breaks JPMS by duplicating the module name jakarta.mail and results in ServiceLoader failure in projects which include dependencies which requires jakarta.mail and ship a compile dependency on the API artefact.

This can cause hard to debug problems even when jars are on the classpath. JPMS helps here in terms of failing fast in case different jars of the same library are there in the dependency tree. 

> FWIW this was all caused by Spring Boot including org.eclipse.angus:jakarta.mail as a dependency instead of org.eclipse.angus:angus-mail while also depending upon jakarta.mail:jakarta.mail-api.

This is exactly the case where having the same module name for both artifacts helps - it allows you to configure/fix the dependency tree the way you want it. Do you want to use correct maven-way standalone API with runtime on the runtime path only? Just exclude offending dependency from spring boot artifacts. Do you prefer to have a "bundle", so the runtime is there for tests out-of-the-box? Exclude APIs from any other dependencies. As long as one does not mix these two different "trees", one can be arbitrarily switching them without the need of updating/rebuilding 3rd party libs, like spring boot

**Comment by dwhitla** [comment]
We had already established that the issue was misidentification of your "bundle" JAR as the RI. I accepted responsibility for that above and closed the issue. Why are you still going on?

> does not answer any question in the bug report template which apparently had to be ignored; 
Your bug report template required detail that was irrelevant when the nature of the issue was easily expressed with a single sentence. You should try filling in your template yourself some time.

> pointer to the documentation which lists possible usage scenarios was given in the initial comment, given the response which followed - was likely ignored as well. 
Your initial response was not ignored. I had already visited the provided URL but due to the expectations I already had at the time the information I needed did not jump out at me. I explained the reason for this above. 
Yes this was a me problem.

> The way the initial report was written demands someone to just do the work ignoring whatever options the project offers and more importantly documents, giving impression project maintainers are ..., nothing else.
No the report was a polite request. @pzygielo managed to answer it simply without being a dick.

> > Also breaks JPMS by duplicating the module name jakarta.mail and results in ServiceLoader failure in projects which include dependencies which requires jakarta.mail and ship a compile dependency on the API artefact.
> 
> This can cause hard to debug problems even when jars are on the classpath. JPMS helps here in terms of failing fast in case different jars of the same library are there in the dependency tree.
I already addressed this above "My last comment about JPMS and ServiceLoader is also based upon trying to use the bundle in an application where other dependencies already declare requires on the API module."
It does not fail fast in the scenario I described which is why I mentioned it. It is shading JARs that causes such hard to debug problems which was the reason for this report. 

> 
> > FWIW this was all caused by Spring Boot including org.eclipse.angus:jakarta.mail as a dependency instead of org.eclipse.angus:angus-mail while also depending upon jakarta.mail:jakarta.mail-api.
> 
> This is exactly the case where having the same module name for both artifacts helps - it allows you to configure/fix the dependency tree the way you want it.
No this is exactly the case that caused the problem. Spring Boot incorrectly pulls in both the API JAR and your bunlde.  "Just exclude offending dependency from spring boot artifacts" in a real-world-scale project is non-trivial.

**Comment by dwhitla** [comment]
Perhaps something was lost in translation. For clarity:
- I closed this issue upon realising I had mistakenly been using the "bundle" JAR instead of your RI.
- This project has resolved the long standing issue of its predecessors of shading the API classes in the RI artefact.
- I have no issue with the "bundle" existing.
- Everything works as expected when using `org.eclipse.angus:angus-mail` with `jakarta.mail:jakarta.mail-api`.
Thank you.
