### ISSUE TITLE
Are jakarta-mail and angus-mail the same software? Are API compatible?

### ISSUE THREAD

**Issue by nomoreyou** [eclipse-ee4j/angus-mail#113]
hi @lukasj my team got a problem with jakatal mail@2.0.1 software and we want replace it with angus-mail.but i dont know what different between it。Can I replace the reference coordinates of jakarta-mail directly in the pom.xml and not need to change the code? thank you very much.

**Comment by verhasi** [comment]
Hi @nomoreyou 

Looking at the documentation at https://eclipse-ee4j.github.io/angus-mail/ you can see

> August 18, 2021 - Jakarta Mail moves to Eclipse Angus
> To break tight integration between Jakarta Mail Specification API and the implementation, sources of 
> the implementation were moved to this project and further development continues here. Angus Mail is 
> the direct successor of JavaMail/JakartaMail.

Also on this page I see some bug fixes. 
Summarizing yes you can change the coordinates without the source code modification **if you have no direct dependencies on the com.sun.mail prefixed modules/packages**. Check the imports in the java files recursively and how you get the Store and/or Transport instances.

Best regards,
Istvan

**Comment by nomoreyou** [comment]
@verhasi thank you i got it
