### ISSUE TITLE
Cannot parse messages without a session

### ISSUE THREAD

**Issue by OrangeDog** [eclipse-ee4j/angus-mail#121]
**Describe the bug**
It used to be the case that you could parse `MimeMessage`s without any session, for an application that doesn't need to send or receive email itself.

This ability has been lost at some point in the migration from `com.sun.mail` to `org.eclipse.angus`.

**To Reproduce**
This code works if using `com.sun.mail:mailapi:2.0.1`:

```java
String text = """
    From: user@example.com\r
    To: user@example.com\r
    Subject: Testing\r
    Date: Thu, 01 Jul 2021 12:11:25 +0000 (UTC)\r
    Content-Type: text/plain\r
    \r
    Best ever test content.\r
    """;
InputStream inputStream = new ByteArrayInputStream(text.getBytes())
MimeMessage mimeMessage = new MimeMessage(null, inputStream);
mimeMessage.getContent();
```

If using `org.eclipse.angus:jakarta.mail:2.0.2` it throws:

```stacktrace
jakarta.mail.MessagingException: No inputstream from datasource
;
  nested exception is:
	java.lang.NullPointerException: Cannot invoke "jakarta.mail.Session.getStreamProvider()" because "this.session" is null
	at jakarta.mail.internet.MimeMultipart.parse(MimeMultipart.java:586)
	at jakarta.mail.internet.MimeMessage.getContent(MimeMessage.java:1522)
	at com.example.Test.test(Test.java:28)
```

**Expected behavior**
A session only being necessary if connecting to a server of some kind. Code compatibility with older releases.

**Additional information**
- `org.eclipse.angus:jakarta.mail:1.0.0` throws the same exception
- `jakarta.mail:jakarta.mail-api:2.1.2` throws `java.lang.IllegalStateException: Not provider of jakarta.mail.util.StreamProvider was found`  [sic]
- `jakarta.mail:jakarta.mail-api:2.0.1` throws `java.lang.NoClassDefFoundError: com/sun/mail/util/FolderClosedIOException`
- `com.sun.mail:jakarta.mail:2.0.1` works successfully

**Comment by OrangeDog** [comment]
Using an "empty" session appears to work. It doesn't appear to try to connect to anything with the example above.
```java
Session session = Session.getInstance(new Properties());
```

**Comment by jmehrens** [comment]
For jakarta.mail:jakarta.mail-api:2.1.2 it looks like you are missing the Angus dependencies.

There are 4 jars that have to be added:
angus-activation-XXX.jar,
angus-mail-XXX.jar
jakarta.mail-api-XXX.jar
jakarta.activation-api-XXX.jar

The "java.lang.IllegalStateException: Not provider of jakarta.mail.util.StreamProvider" is usually missing dependencies.
The NullPointerException is a cascading failure.  See: https://github.com/jakartaee/mail-api/issues/550#issuecomment-823008354

If you missing those dependencies in your test case then add them and retest.

**Comment by OrangeDog** [comment]
> you are missing the Angus dependencies

My point is that in the previous version you did not need those dependencies. `mailapi` was sufficient to parse MIME messages.

**Comment by jmehrens** [comment]
@OrangeDog Yes I was able to gather that when I dug deeper into the code. My initial understanding was incorrect.  Because of that I fixed this.  Thank you for reporting this!
