### ISSUE TITLE
`mail.smtp.from` property seems to be ignored

### ISSUE THREAD

**Issue by NicolaIsotta** [eclipse-ee4j/angus-mail#137]
[According to the specifications](https://jakartaee.github.io/mail-api/FAQ#smtpfrom) (also [here](https://github.com/eclipse-ee4j/angus-mail/blob/57bf854c442857769e6852e0d8b8de4ea47a2d61/providers/smtp/src/main/java/org/eclipse/angus/mail/smtp/package-info.java#L247)):

> The `mail.smtp.from` property can be used to set the SMTP FROM: attribute.

However it seems like the property is ignored. I have configured a session with the property valued, then I'm sending a message this way:
```java
Message message = new MimeMessage(mailSession);
message.setRecipient(Message.RecipientType.TO, new InternetAddress("my@mail.org"));
message.setSubject("test");
message.setContent("test", "text/plain");
Transport.send(message);
```
But the message is rejected because it's missing the FROM.
If instead I do this:
```java
Message message = new MimeMessage(mailSession);
message.setRecipient(Message.RecipientType.TO, new InternetAddress("my@mail.org"));
message.setSubject("test");
message.setContent("test", "text/plain");
message.setFrom(new InternetAddress(mailSession.getProperty("mail.smtp.from")));
Transport.send(message);
```
The FROM is correctly valued.

Is this a bug in the implementation?

_Originally posted by @NicolaIsotta in https://github.com/eclipse-ee4j/angus-mail/discussions/135_

**Comment by jmehrens** [comment]
From your links:
>Email address to use for SMTP MAIL command.  This sets the envelope return address.  Defaults to msg.getFrom() or InternetAddress.getLocalAddress().  NOTE: mail.smtp.user was previously used for this.

The mail.smtp.from sets the return-to address.
What is a [return address](https://github.com/eclipse-ee4j/angus-mail/blob/57bf854c442857769e6852e0d8b8de4ea47a2d61/providers/smtp/src/main/java/org/eclipse/angus/mail/smtp/SMTPMessage.java#L120) 

>Set the From address to appear in the SMTP envelope.  Note that this is different than the From address that appears in the message itself.  The envelope From address is typically used when reporting errors. See <A HREF="http://www.ietf.org/rfc/rfc821.txt">RFC 821</A> for details. <p>

Use this property to control where delivery error (dsn package) are reported.  Setting this property does not control the mimemessage from attribute.

**Comment by NicolaIsotta** [comment]
Thanks for the clarification.
So, is there any way to set the default message from using the session object?

**Comment by jmehrens** [comment]
>So, is there any way to set the default message from using the session object?

You always have to call a method on the Message/MineMessage.  That said,  Message has a no argument serFrom method that uses the [InternetAddress::getLocalAddress​](https://jakarta.ee/specifications/mail/2.1/apidocs/jakarta.mail/jakarta/mail/internet/internetaddress#getLocalAddress(jakarta.mail.Session)).  If you always call that method on each message it will compute the local address.  You can set `mail.from` to set the local email address, which is most likely what you want.  This method also allows you to set nothing in the session properties and it will compute a default email adress (see the docs).  Works great if your org has well defined usernames and domains that match assigned email address. You can even do some dynamic tricks to use the user name of the JVM process but override the `mail.host` to control the domain part.  Then set `mail.smtp.host` so the code connects to the correct server.  Lots of combinations and properties to change here.

Like your second example, it is fine to call Session::getProperty or Properties::getProperty to read `mail.from` (as opposed to `mail.smtp.from`) as the message from address attribute of a message.  If you go this route, consider adding a namespace in front of your keys that is your appname or something.   E.G. `session.getProperty("myappname.mail.from")` or `session.getProperty("myappname.mail.to")`.

**Comment by NicolaIsotta** [comment]
Got it. Thanks.
