### ISSUE TITLE
org.eclipse.angus.mail bundle fails to resolve under OSGi due to mandatory 'sun.security.util' package 

### ISSUE THREAD

**Issue by HannesWell** [eclipse-ee4j/angus-mail#15]
**Describe the bug**
When using the Maven module `org.eclipse.angus:angus-mail:1.0.0` as an OSGi bundle in an OSGi-application like Eclipse respectively Equinox, the bundle fails to resolve due to the unsatisfied constraint `Import-Package sun.security.util`.

Comparing with [`com.sun.mail:jakarta.mail:2.0.1`](https://mvnrepository.com/artifact/com.sun.mail/jakarta.mail/2.0.1) reveals that the Package-Import `Import-Package sun.security.util` was optional there but is not optional for `org.eclipse.angus:angus-mail`.

First I suspected a missing BND instruction in your configuration of the `maven-bundle-plugin` that generates the MANIFEST.MF, but while preparing this issue I noticed that a corresponding instruction exist (even before the 1.0.0 release):
https://github.com/eclipse-ee4j/angus-mail/blob/863616735b2f9732b5f32ddae050d5471c2a25d6/providers/pom.xml#L65

Nevertheless in the `META-INF/MANIFEST.MF` from the jar available from Maven-Central the following `Import-Package` header specified that, declares the package `sun.security.util` as mandatory:
```
Import-Package: com.sun.mail.auth;version="[1.0,2)",com.sun.mail.iap;ver
 sion="[1.0,2)",com.sun.mail.imap;version="[1.0,2)",com.sun.mail.imap.pr
 otocol;version="[1.0,2)",com.sun.mail.util;version="[1.0,2)",jakarta.ac
 tivation;version="[2.1,3)",jakarta.mail;version="[2.1,3)",jakarta.mail.
 event;version="[2.1,3)",jakarta.mail.internet;version="[2.1,3)",jakarta
 .mail.search;version="[2.1,3)",jakarta.mail.util;version="[2.1,3)",java
 x.crypto,javax.crypto.spec,javax.net,javax.net.ssl,javax.security.auth.
 callback,javax.security.auth.x500,javax.security.sasl,javax.xml.transfo
 rm,javax.xml.transform.stream,sun.security.util
```

I cannot tell why the `maven-bundle-plugin` configuration is ignored, but it looks like there is a problem in the build process.

**To Reproduce**
In the Eclipse IDE with (PDE and m2e installed), create a project that contains a target-platform like the following and set it as active target-platform.
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="target">
		<location includeDependencyDepth="infinite" includeDependencyScopes="compile,provided,runtime,import" includeSource="true" label="Mail dependencies" missingManifest="generate" type="Maven">
			<dependencies>
				<dependency>
					<groupId>org.eclipse.angus</groupId>
					<artifactId>angus-mail</artifactId>
					<version>1.0.0</version>
					<type>jar</type>
				</dependency>
			</dependencies>
		</location>
	</locations>
</target>
```
Open the `Target-Platform State` view and select "Show only unresolved plug-ins" as displayed in the screenshot below.
Create a Eclipse Application launch that includes the Plug-in/Bundle `org.eclipse.angus.mail` to get the failed launch validation from the screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/44067969/158559609-851d017b-dcf6-4f05-bf80-2c6b8ea6b57e.png)

![image](https://user-images.githubusercontent.com/44067969/158556767-bd813175-988b-4148-bdb7-90ea89687cc4.png)

**Desktop (please complete the following information):**
 - OS: Windows-10, Linux Debian

**Comment by HannesWell** [comment]
While trying out `org.eclipse.angus:jakarta.mail` I noticed a similar issue. The package `sun.security.util` is a mandatory requirement there too.

I assume this is caused by the configuration of the maven-bundle-plugin that does not consider the parent config for `Import-Package` introduced in https://github.com/eclipse-ee4j/angus-mail/pull/19:

https://github.com/eclipse-ee4j/angus-mail/blob/7b2da45e8060cbdedaac7c61a832863fc74c1f74/providers/jakarta.mail/pom.xml#L195-L198

@jbescos and @lukasj could you be so kind and have a look at that as well? Thanks in advance.

**Comment by precoder** [comment]
With version of 2.0.2 on default mail provider (jakarta.mail.jar) I get in the Manifest:
org.graalvm.nativeimage.hosted;resolution:=optional,sun.security.util

Is sun.security.util again mandatory?
If it is mandatory where can I find a JAR that exports this package?

**Comment by lukasj** [comment]
@HannesWell @precoder - if you see a problem, either create new issue or reopen existing one; everything else can easily be missed and/or ignored

**Comment by precoder** [comment]
Thanks for quick response, I will do a new issue 👍
