### ISSUE TITLE
Can't use special characters in passwords

### ISSUE THREAD

**Issue by adabugra** [eclipse-ee4j/angus-mail#152]
**Describe the bug**
If I use a password that contains characters like (*^%#}{_\|~<>€$£•!?), mail does not get sent.

**To Reproduce**

1. Use a password with special characters
2. Send the mail
3. Mail not gets sent

**Expected behavior**
Mail to be sent

**Screenshots**
![image](https://github.com/user-attachments/assets/4b1db76b-ae9e-48fc-8b31-e3e727cb2bdc)

**Desktop (please complete the following information):**

- OS: Ubuntu and Windows
- Browser -
- Version 22.04
**Mail server:**

- Protocol being used: SMTP
- Vendor/product: promail.com.tr (happens on all providers)

**Comment by jmehrens** [comment]
You should post the full debug log in text form. The log you are showing is [normal output](https://github.com/eclipse-ee4j/angus-mail/issues/109#issuecomment-1712820279) and is not a failure.

**Comment by jmehrens** [comment]
@adabugra there should be a client side error in the debug logs or a server side error in the server logs as to why your mail was not sent.  What you attached is the wrong section of the logs.
