### ISSUE TITLE
Simple SMTP Send Worked with JavaMail, Fails with Angus 1.0.0

### ISSUE THREAD

**Issue by cayhorstmann** [eclipse-ee4j/angus-mail#50]
**Describe the bug**
The demo program from the Core Java book worked with Java Mail but hangs with Jakarta Mail when sending SMTP to FastMail.

**To Reproduce**

1. Place the program below into a `mail` directory. 
2. Change `javax` to `jakarta` and uncomment the `setDebug` line
3. Make a file `mail/mail.properties` with the lines
    mail.transport.protocol=smtps
    mail.smtps.auth=true
    mail.smtps.host=smtp.fastmail.com
    mail.smtps.user=(username)
4. Gather files jakarta.activation-api-2.1.0.jar and  jakarta.mail-1.0.0.jar in a `jars` directory
5. Compile with `javac -cp .:jars mail/MailTest.java`
6. Make a file `message.txt` whose first three lines are the sender, recipient, and subject, and the rest the message body.
7. Run with `MAIL_PASSWORD=(password) java -cp .:jars mail.MailTest message.txt` 

**Expected behavior**

The mail is delivered to its recipient

**Actual behavior**

The program hangs for a long time after `QUIT` and then throws an exception

```
DEBUG: setDebug: Jakarta Mail version ${mail.version}
DEBUG: getProvider() returning jakarta.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth true
DEBUG SMTP: trying to connect to host "smtp.fastmail.com", port 465, isSSL true
220 smtp.fastmail.com ESMTP ready
DEBUG SMTP: connected to host "smtp.fastmail.com", port: 465
EHLO cay-ThinkPad-X1-Yoga-Gen-7
250-smtp.fastmail.com
250-PIPELINING
250-SIZE 71000000
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 AUTH PLAIN LOGIN XOAUTH2 OAUTHBEARER
DEBUG SMTP: Found extension "PIPELINING", arg ""
DEBUG SMTP: Found extension "SIZE", arg "71000000"
DEBUG SMTP: Found extension "ENHANCEDSTATUSCODES", arg ""
DEBUG SMTP: Found extension "8BITMIME", arg ""
DEBUG SMTP: Found extension "AUTH", arg "PLAIN LOGIN XOAUTH2 OAUTHBEARER"
DEBUG SMTP: protocolConnect login, host=smtp.fastmail.com, user=cayhorstmann@fastmail.fm, password=<non-null>
DEBUG SMTP: Attempt to authenticate using mechanisms: LOGIN PLAIN DIGEST-MD5 NTLM XOAUTH2 
DEBUG SMTP: Using mechanism LOGIN
DEBUG SMTP: AUTH LOGIN command trace suppressed
DEBUG SMTP: AUTH LOGIN succeeded
DEBUG SMTP: use8bit false
MAIL FROM:<cay@horstmann.com>
250 2.1.0 Ok
RCPT TO:<cay.horstmann@sjsu.edu>
250 2.1.5 Ok
DEBUG SMTP: Verified Addresses
DEBUG SMTP:   Cay Horstmann <cay.horstmann@sjsu.edu>
DATA
354 End data with <CR><LF>.<CR><LF>
QUIT
DEBUG SMTP: EOF: [EOF]
Exception in thread "main" java.lang.RuntimeException: Provider for jakarta.activation.spi.MailcapRegistryProvider cannot be found
	at jakarta.activation.FactoryFinder.find(FactoryFinder.java:90)
	at jakarta.activation.MailcapCommandMap.getImplementation(MailcapCommandMap.java:696)
	at jakarta.activation.MailcapCommandMap.loadFile(MailcapCommandMap.java:284)
	at jakarta.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:154)
	at jakarta.activation.CommandMap.getDefaultCommandMap(CommandMap.java:60)
	at jakarta.activation.DataHandler.getCommandMap(DataHandler.java:128)
	at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:590)
	at jakarta.activation.DataHandler.writeTo(DataHandler.java:290)
	at jakarta.mail.internet.MimeUtility.getEncoding(MimeUtility.java:316)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1580)
	at jakarta.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2265)
	at jakarta.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2225)
	at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1904)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1332)
	at mail.MailTest.main(MailTest.java:55)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Mail server:**
 - Protocol being used: smtps
 - Vendor/product: FastMail
 - Mail service URL: fastmail.com

**Additional context**
Here is the program from the Core Java book:
```
package mail;

import java.io.*;
import java.nio.charset.*;
import java.nio.file.*;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.mail.internet.MimeMessage.RecipientType;

/**
 * This program shows how to use JavaMail to send mail messages.
 * @author Cay Horstmann
 * @version 1.01 2018-03-17
 */
public class MailTest
{
   public static void main(String[] args) throws MessagingException, IOException
   {
      var props = new Properties();
      try (InputStream in = Files.newInputStream(Paths.get("mail", "mail.properties")))
      {
         props.load(in);
      }
      List<String> lines = Files.readAllLines(Paths.get(args[0]), StandardCharsets.UTF_8);
       
      String from = lines.get(0);
      String to = lines.get(1);
      String subject = lines.get(2);
      
      var builder = new StringBuilder();
      for (int i = 3; i < lines.size(); i++)
      {
         builder.append(lines.get(i));
         builder.append("\n");
      }

      String password = System.getenv("MAIL_PASSWORD");
      if (password == null) {
         Console console = System.console();
         password = new String(console.readPassword("Password: "));
      }
      
      Session mailSession = Session.getDefaultInstance(props);
      // mailSession.setDebug(true);
      var message = new MimeMessage(mailSession);
      message.setFrom(new InternetAddress(from));
      message.addRecipient(RecipientType.TO, new InternetAddress(to));
      message.setSubject(subject);
      message.setText(builder.toString());
      Transport tr = mailSession.getTransport();
      try
      {
         tr.connect(null, password);
         tr.sendMessage(message, message.getAllRecipients());
      }
      finally
      {
         tr.close();
      }

   }
}
```

**Comment by jbescos** [comment]
Hi @cayhorstmann 

You have to include also angus-activation-1.0.0.jar in your classpath.

**Comment by cayhorstmann** [comment]
Thanks, that solved it. I was confused by the fact that jakarta-mail.jar has both the API and the implementation and somehow expected the same for the activation jar. With more caffeine I now see the -api in the name :-)  

I also found out that https://eclipse-ee4j.github.io/angus-mail/ recommends to use angus-mail.jar and jakarta.mail-api.jar. Consider adding angus-activation.jar and  jakarta.activation-api.jar to the first table of that page! 

Finally, since jakarta-mail.jar is intended as a single jar, why not include the activation code with it?

**Comment by jbescos** [comment]
That https://eclipse-ee4j.github.io/angus-mail/ needs an update. The dependency is also misspelled, we will need to update that. But I think we don't need to add there activation api and the implementation, because they come as a transitive dependency.

Just adding this dependency:
```
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>jakarta.mail</artifactId>
    <version>1.1.0</version>
</dependency>
```

That brings as a transitive dependency the activation api and implementation:
```
[INFO] \- org.eclipse.angus:jakarta.mail:jar:1.1.0:compile
[INFO]    +- jakarta.activation:jakarta.activation-api:jar:2.1.1:compile
[INFO]    \- org.eclipse.angus:angus-activation:jar:1.1.0:runtime
```

But it is true, that if you don't use Maven, you cannot figure out that depends on activation. You can still check the dependencies of it here: https://mvnrepository.com/artifact/org.eclipse.angus/jakarta.mail/1.1.0

That jakarta-mail.jar is supposed to contain only the api and the default implementation (angus-mail). I think there are no plans to include activation api and implementation too.

**Comment by lukasj** [comment]
I have added a note about the activation on the web.

Note that there are 3 different ways of using project provided jar files and each way is suitable for different usecase.
