### ISSUE TITLE
Documentation: conflicting changelogs

### ISSUE THREAD

**Issue by XSpielinbox** [eclipse-ee4j/angus-mail#57]
**Describe the bug**
When looking for a changelog, I found two conflicting ones: one listing the next release after 1.0.0 as [1.1.0](https://github.com/eclipse-ee4j/angus-mail/blob/master/doc/src/main/resources/docs/CHANGES.txt) and one listing it as [1.0.1](https://eclipse-ee4j.github.io/angus-mail/docs/CHANGES.txt). The former also lists many changes more than the latter.
They refer to the same source, however (though this source links to a 404 page).

**Expected behavior**
There changelog on the website (under https://eclipse-ee4j.github.io/angus-mail) is exactly the same as the GitHub Source code.

**Comment by lukasj** [comment]
this gets fixed automagically once the next releases - which is already prepared [in staging](https://jakarta.oss.sonatype.org/content/groups/staging/org/eclipse/angus/angus-mail/1.1.0/) - [gets approved](https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/429)

**Comment by lukasj** [comment]
done
