### ISSUE TITLE
Spring Boot 3: Provider for jakarta.activation.spi.MailcapRegistryProvider cannot be found

### ISSUE THREAD

**Issue by miriyalajanardhan** [eclipse-ee4j/angus-mail#63]
Getting error upon sending email in a Spring Boot 3 application. 

```
org.springframework.mail.MailSendException: Failed messages: java.lang.RuntimeException: Provider for jakarta.activation.spi.MailcapRegistryProvider cannot be found
        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:491)
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361)
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356)
```

We are using JavaMailSender to send the email.

Have the below dependency already.

```xml
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
</dependency>
```

Here's my code:

```java
private final JavaMailSender mailSender;
    
    
    private void sendEmail () {
    
        MimeMessage message = mailSender.createMimeMessage();
    
        MimeMessageHelper messageHelper = new MimeMessageHelper(message, false, StandardCharsets.UTF_8.name());
        messageHelper.setTo("testemail@test.com");
        messageHelper.setSubject("test subject");
        messageHelper.setText("sample html email content", true);
        mailSender.send(message);
        
    }
```

**Comment by lukasj** [comment]
dependency on `org.eclipse.angus:angus-activation`, version 1.0.0 or newer at least on the runtime scope is required.

**Comment by miriyalajanardhan** [comment]
This is the dependency tree, which is already there.

[INFO] +- org.springframework.boot:spring-boot-starter-mail:jar:3.0.1:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:3.0.1:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:3.0.1:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:3.0.1:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.4.5:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.4.5:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.19.0:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:2.0.6:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.33:compile
[INFO] |  +- org.springframework:spring-context-support:jar:6.0.3:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:6.0.3:compile
[INFO] |  |  \- org.springframework:spring-context:jar:6.0.3:compile
[INFO] |  \- org.eclipse.angus:jakarta.mail:jar:1.0.0:compile
[INFO] |     +- jakarta.activation:jakarta.activation-api:jar:2.1.0:compile
[INFO] |     \- org.eclipse.angus:angus-activation:jar:1.0.0:runtime

**Comment by lukasj** [comment]
I've tried simple demo app and email is being sent successfully with no exception, in the other words I'm not able to reproduce the error you see with the same dependencies.
