### ISSUE TITLE
I can not build project

### ISSUE THREAD

**Issue by leonardwoo** [eclipse-ee4j/angus-mail#69]
I can't compile the project because the module cannot be found.

`org.seppiko.commons:commons-mail`
Code: https://gitlab.com/seppiko/commons-mail/-/tree/dev

**Comment by lukasj** [comment]
works for me with the release profile which fixes `Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project commons-mail: Compilation failure: Compilation failure: ` problem by using the right version of the compiler - that is nothing this project can help you with.
