### ISSUE TITLE
Inconsistent Java version requirements

### ISSUE THREAD

**Issue by ppkarwasz** [eclipse-ee4j/angus-mail#76]
**Describe the bug**
The Java bytecode version of Angus Mail artifacts unexpectedly changed to Java 9 in version 2.0.0, whereas the OSGI requirements are still the same:

```
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
```

Since:
 * version 2.0.0 explicitly solves #37, which does not occur on Java 11 and higher,
 *  the OSGI requirement is Java 8,
 * module descriptors can be safely added to otherwise Java 8 libraries (cf. this is what [BND does](https://bnd.bndtools.org/chapters/330-jpms.html#java-8-support) for example),

I believe that Angus Mail should be recompiled with Java 8 bytecode.

**Comment by jbescos** [comment]
That was my mistake, I will fix it.

**Comment by ppkarwasz** [comment]
@jbescos,

Thanks for the ultrafast fix.
