### ISSUE TITLE
mail.smtp.*.checkserveridentity default not like described in SSLNotes

### ISSUE THREAD

**Issue by demarco88** [eclipse-ee4j/angus-mail#86]
Hi. 
We use java mail in production actual with version 1.6.4. Now we want to migrate to 2.1.1.
The default of the mail.*.ssl.checkserveridentity seems to be changed. In previous releases it was false. And now it seems to be true.
Problem with this change: There is no compatibility with earlier releases!
Our problem now, we must adapt several delivered configurations of our customers....

This should be at least be announced in the ReleaseNotes. But in contrast. SSLNOTES.txt (also part of mail api specification) said:

-- Server Identity Check

RFC 2595 specifies addition checks that must be performed on the
server's certificate to ensure that the server you connected to is
the server you intended to connect to.  This reduces the risk of
"man in the middle" attacks.  **For compatibility with earlier releases
of Jakarta Mail, these additional checks are disabled by default.**  We
strongly recommend that you enable these checks when using SSL.  To
enable these checks, set the "mail.<protocol>.ssl.checkserveridentity"
property to "true".

API-Docs seems to be changed. Please adapt the complete documentation and/or the api documentation of jakarta mail api specifikation documentation.
thx and best regards

**Comment by lukasj** [comment]
see https://eclipse-ee4j.github.io/angus-mail/docs/COMPAT.txt

**Comment by demarco88** [comment]
thx. ok....one document more which tells each other some opposites :-)
COMPAT.txt is only available to those who have checkout the git project?!
I think the most people reading the release notes which are directly reachable over the website...

**Comment by lukasj** [comment]
https://eclipse-ee4j.github.io/angus-mail is project web site, not a git repo. In the Download Angus Mail Release section of the page, there are pointers to various documents, including `COMPAT.txt` described as _Important notes about compatibility_

**Comment by demarco88** [comment]
ok; i see. all doucments are also linked in the project side. thanks for the info.
thread can be closed in the hope that anyone is reading the right document with the right content.
